export const linguagens = {
    java : {name: "Java", img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg"},
    python :{name: "Python", img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg"},
    CSharp : {name: "C#", img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/csharp/csharp-original.svg"},
    Flutter : {name: "Flutter", img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/flutter/flutter-original.svg"},
    JavaScript : {name: "JavaScript", img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg"},
    TypeScript : {name: "TypeScript", img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg"},
    Reactjs : {name: "React JS", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg"},
    ReactNative : {name: "React Native", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg"},
    NextJs : {name: "Next.JS", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg"},
    NodeJs : {name: "Node.JS", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original-wordmark.svg"},
    PHP : {name: "PHP", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg"},
    Delphi : {name: "Delphi", img:"https://cdn-icons-png.flaticon.com/512/5968/5968252.png"},
    StyledCompo : {name: "Styled Components", img:"https://styled-components.gallerycdn.vsassets.io/extensions/styled-components/vscode-styled-components/1.7.8/1680721633849/Microsoft.VisualStudio.Services.Icons.Default"},
    TailWind : {name: "TailWind", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg"},
    MaterialUI : {name: "Material UI", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/materialui/materialui-original.svg"},
    BootStrap : {name: "BootStrap", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-original.svg"},
    Axios : {name: "Axios", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/axios/axios-plain.svg"},
    APIRest : {name: "API Rest", img:"https://miro.medium.com/v2/resize:fit:600/1*1S1FzR-yg-ucZGMoxCC9hw.png"},
    GitHub : {name: "GitHub", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg"},
    Git : {name: "Git", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg"},
    Postman : {name: "Postman", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postman/postman-original.svg"},
    MySQl : {name: "MySQl", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original-wordmark.svg"},
    SQlite : {name: "SQlite", img:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sqlite/sqlite-original-wordmark.svg"},

          
 }